# Generated by Django 5.1.3 on 2024-11-22 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6, verbose_name='Gender')),
                ('father', models.ForeignKey(blank=True, limit_choices_to={'gender': 'male'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fathers_children', to='core.human', verbose_name='Father')),
                ('mother', models.ForeignKey(blank=True, limit_choices_to={'gender': 'female'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mothers_children', to='core.human', verbose_name='Mother')),
            ],
        ),
    ]
